export const datatableOffer = [
    {
        phone_id: 101,
        promo_id: "PROMO001",
        name: "Wireless Earbuds",
        promo_name: "New Year Sale",
        price: "$49.99",
        price_discount: "$10.00",
        discount_percentage: "20%",
        end_date: "2025-02-01",
    },
    {
        phone_id: 102,
        promo_id: "PROMO002",
        name: "Smartphone",
        promo_name: "Flash Deal",
        price: "$699.99",
        price_discount: "$50.00",
        discount_percentage: "7%",
        end_date: "2025-03-15",
    },
    {
        phone_id: 103,
        promo_id: "PROMO003",
        name: "Gaming Laptop",
        promo_name: "Holiday Sale",
        price: "$1299.99",
        price_discount: "$150.00",
        discount_percentage: "11%",
        end_date: "2025-02-28",
    },
    {
        phone_id: 104,
        promo_id: "PROMO004",
        name: "Bluetooth Speaker",
        promo_name: "Clearance",
        price: "$99.99",
        price_discount: "$20.00",
        discount_percentage: "20%",
        end_date: "2025-01-31",
    },
    {
        phone_id: 105,
        promo_id: "PROMO005",
        name: "4K TV",
        promo_name: "Mega Sale",
        price: "$899.99",
        price_discount: "$100.00",
        discount_percentage: "11%",
        end_date: "2025-04-01",
    },
    {
        phone_id: 106,
        promo_id: "PROMO006",
        name: "Fitness Tracker",
        promo_name: "Spring Discount",
        price: "$79.99",
        price_discount: "$15.00",
        discount_percentage: "19%",
        end_date: "2025-03-10",
    },
    {
        phone_id: 107,
        promo_id: "PROMO007",
        name: "Air Conditioner",
        promo_name: "Summer Prep",
        price: "$499.99",
        price_discount: "$50.00",
        discount_percentage: "10%",
        end_date: "2025-05-15",
    },
    {
        phone_id: 108,
        promo_id: "PROMO008",
        name: "Gaming Console",
        promo_name: "Exclusive Deal",
        price: "$399.99",
        price_discount: "$25.00",
        discount_percentage: "6%",
        end_date: "2025-06-01",
    },
    {
        phone_id: 109,
        promo_id: "PROMO009",
        name: "Electric Scooter",
        promo_name: "Eco Ride Sale",
        price: "$349.99",
        price_discount: "$50.00",
        discount_percentage: "14%",
        end_date: "2025-02-20",
    },
    {
        phone_id: 110,
        promo_id: "PROMO010",
        name: "Wireless Keyboard",
        promo_name: "Tech Essentials",
        price: "$59.99",
        price_discount: "$5.00",
        discount_percentage: "8%",
        end_date: "2025-03-25",
    },
];

export const datatableOrder = {
    data: [
        {
            phone_id: 1,
            order_id: "ORD001",
            username: "John Doe",
            address: "123 Main St, Springfield",
            order_date: "2023-12-01T10:30:00Z",
            total_amount: "$120.50",
        },
        {
            phone_id: 2,
            order_id: "ORD002",
            username: "Jane Smith",
            address: "456 Elm St, Shelbyville",
            order_date: "2023-12-02T14:00:00Z",
            total_amount: "$89.99",
        },
        {
            phone_id: 3,
            order_id: "ORD003",
            username: "Alice Johnson",
            address: "789 Oak St, Capital City",
            order_date: "2023-12-03T18:45:00Z",
            total_amount: "$150.00",
        },
        {
            phone_id: 4,
            order_id: "ORD004",
            username: "Bob Brown",
            address: "101 Maple St, Ogdenville",
            order_date: "2023-12-04T12:15:00Z",
            total_amount: "$60.75",
        },
        {
            phone_id: 5,
            order_id: "ORD005",
            username: "Charlie Green",
            address: "202 Pine St, North Haverbrook",
            order_date: "2023-12-05T09:20:00Z",
            total_amount: "$210.99",
        },
    ],
};
